Add SBCL and ASDF version info to README
Lisp-Stat/lisp-stat pull request #14
Opened 2022-08-05 12:19 UTC by HM0880

The lowest-supported versions should also go in the website docs, but I do not know where those files are.

2022-08-05 12:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Lisp-Stat/lisp-stat?pullRequest=14) <br/>All committers have signed the CLA.

2022-08-05 15:43 UTC, vindarel commented
FWIW I had to upgrade ASDF to version 3.3.5 for a CI on another project, here's a one-liner:

    ( cd ~/common-lisp/ && wget https://asdf.common-lisp.dev/archives/asdf-3.3.5.tar.gz  && tar -xvf asdf-3.3.5.tar.gz && mv asdf-3.3.5 asdf )

2022-08-06 01:28 UTC, Symbolics commented on README.md
> +  (read-csv #P"LS:DATASETS;sg-weather.csv"))
I just noted a problem here. It should now be #P"LS:DATA;sg-weather.csv". Could you please update this line as well?

2022-08-06 01:30 UTC, Symbolics requested changes
I just added a comment on line 186 to address a change made in standard directory structure.  Other than that it looks good.  It would be nice if we could incorporate vindral's one-line upgrade into the README for folks that will need it.

2022-09-05 13:06 UTC, snunez1 commented
@HM0880, do you need help with the CLA? I'd like to merge this before I push up some changes.

2022-09-06 20:33 UTC, HM0880 commented
@snunez1 Just signed the CLA; sorry for the delay!

2022-09-06 20:53 UTC, HM0880 commented
@Symbolics @snunez1 

Just updated the data path (https://github.com/HM0880/lisp-stat/commit/6c52d4d6641675d3c604b3f46055ed90306c2067) and added the one-liner (https://github.com/HM0880/lisp-stat/commit/b4da5feb1ca3c00af580ea3a8f2faad29610272f).  Thanks for your patience.

2024-07-30 00:18 UTC, snunez1 commented
My apologies for taking a while on this.  It seems that the ecosystem has fixed the problem that you encountered, so the fixes no longer need to be documented.  I much appreciate the contribution.

2024-07-30 00:18 UTC, closed without merging